apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-k8s-client
  labels:
    app: hdfs-k8s-client
    app-role: big-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hhdfs-k8s-client
      app-role: big-data
  template:
    metadata:
      labels:
        app: hhdfs-k8s-client
        app-role: big-data
      #annotations:
    spec:
      containers:
        - name: hdfs-client
          image: uhopper/hadoop:2.7.2
          env:
            - name: HADOOP_CUSTOM_CONF_DIR
              value: /etc/hadoop-custom-conf
            - name: MULTIHOMED_NETWORK
              value: "0"
          command: ['/bin/sh', '-c']
          args:
            - /entrypoint.sh /usr/bin/tail -f /var/log/dmesg
          volumeMounts:
            - name: hdfs-config
              mountPath: /etc/hadoop-custom-conf
              readOnly: true
            #- name: kerberos-config
            #  mountPath: /etc/krb5.conf
            #  subPath: {{ .Values.global.kerberosConfigFileName }}
            #  readOnly: true
      restartPolicy: Always
      volumes:
        - name: hdfs-k8s-config
          configMap:
            name: hdfs-k8s-config
        #- name: kerberos-config
        #  configMap:
        #    name: {{ template "krb5-configmap" . }}